package dev.dasan.customdungeons.model;

public enum Trigger { EVERY_X_SECONDS, ON_HIT, ON_DAMAGED, HEALTH_BELOW, ON_SPAWN, ON_DEATH, PLAYER_IN_RANGE, ATTACKED_FROM_BEHIND, SURROUNDED, DAMAGE_BURST, RANGED_ATTACK, PLAYER_HEALED, PLAYER_NEAR_DEATH, STRATEGY_DETECTED }
